services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exampledb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - example-network
    ports:
      - 5432:5432

networks:
  example-network:
    driver: bridge

volumes:
  postgres-data: